# Generated by Django 3.1.4 on 2020-12-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('deleted_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_id', models.IntegerField(blank=True, null=True)),
                ('bike_type', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('displacement', models.TextField(blank=True, null=True)),
                ('regis_year', models.IntegerField(blank=True, null=True)),
                ('kms_driven', models.IntegerField(blank=True, null=True)),
                ('no_of_gear', models.IntegerField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('made_of_origin', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('engine_type', models.TextField(blank=True, null=True)),
                ('max_power', models.TextField(blank=True, null=True)),
                ('ground_clereance', models.TextField(blank=True, null=True)),
                ('suspension', models.TextField(blank=True, null=True)),
                ('fueL_tank_capacity', models.TextField(blank=True, null=True)),
                ('brake_system', models.TextField(blank=True, null=True)),
                ('kerb_weight', models.TextField(blank=True, null=True)),
                ('top_speed', models.TextField(blank=True, null=True)),
                ('bore', models.TextField(blank=True, null=True)),
                ('stroke', models.TextField(blank=True, null=True)),
                ('max_torque', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.IntegerField(blank=True, null=True)),
                ('guest_name', models.TextField(blank=True, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_password', models.TextField(blank=True, null=True)),
                ('new_password', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('registrated_at_date', models.TextField(blank=True, null=True)),
                ('login_at_date', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Guest',
            },
        ),
        migrations.CreateModel(
            name='Home_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_id', models.IntegerField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home_slider',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.IntegerField(blank=True, null=True)),
                ('text_box', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Orders_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_id', models.IntegerField(blank=True, null=True)),
                ('pending_payment', models.TextField(blank=True, null=True)),
                ('failed', models.TextField(blank=True, null=True)),
                ('processing', models.TextField(blank=True, null=True)),
                ('completed', models.TextField(blank=True, null=True)),
                ('on_hold', models.TextField(blank=True, null=True)),
                ('cancelled', models.TextField(blank=True, null=True)),
                ('refunded', models.TextField(blank=True, null=True)),
                ('authentication_required', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Orders_status',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_des', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('product_price', models.TextField(blank=True, null=True)),
                ('product_type', models.TextField(blank=True, null=True)),
                ('product_category', models.TextField(blank=True, null=True)),
                ('product_cart_details', models.TextField(blank=True, null=True)),
                ('product_available', models.TextField(blank=True, null=True)),
                ('product_stock', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('deleted_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_categori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('cate_name', models.TextField(blank=True, null=True)),
                ('cate_slug', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('deleted_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product_categori',
            },
        ),
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_password', models.TextField(blank=True, null=True)),
                ('new_password', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('registrated_at_date', models.TextField(blank=True, null=True)),
                ('login_at_date', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('browser', models.TextField(blank=True, null=True)),
                ('browser_version', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('visited_page', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss')),
            ],
            options={
                'verbose_name_plural': 'Traffic',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('permission', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField(blank=True, null=True)),
                ('comments_box', models.TextField(blank=True, null=True)),
                ('review_box', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Reply_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField(blank=True, null=True)),
                ('text_box', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.message')),
            ],
            options={
                'verbose_name_plural': 'Reply_message',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('deleted_at_date', models.TextField(blank=True, null=True)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.cart')),
                ('order_status_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.orders_status')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss'),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('deleted_at_date', models.TextField(blank=True, null=True)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.cart')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.product')),
            ],
            options={
                'verbose_name_plural': 'Cart_item',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(blank=True, null=True)),
                ('blog_name', models.TextField(blank=True, null=True)),
                ('blog_des', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('created_at_date', models.TextField(blank=True, null=True)),
                ('updated_at_date', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangologin.userss')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
